#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { readJson, tokenNameToCssVar, flattenTokens } from "./lib.mjs";

const handoffRoot = path.resolve(process.argv[2] || "./handoff");
const outDir = path.resolve(process.argv[3] || "./apps/web/src/generated");
const bundlePath = path.join(handoffRoot, ".handoff", "build", "handoff.bundle.json");
if (!fs.existsSync(bundlePath)) throw new Error("缺少 bundle，请先执行 npm run dhp:build");
fs.mkdirSync(outDir, { recursive: true });

const bundle = readJson(bundlePath);
fs.copyFileSync(bundlePath, path.join(outDir, "handoff.bundle.json"));

const flat = flattenTokens(bundle.tokens).filter(t => !t.name.startsWith("meta."));
const cssLines = [
  "/* Generated by scripts/sync-web.mjs. Do not edit manually. */",
  ":root {"
];
for (const t of flat) {
  if (typeof t.value === "string" || typeof t.value === "number") {
    cssLines.push(`  ${tokenNameToCssVar(t.name)}: ${t.value};`);
  }
}
cssLines.push("}", "");
fs.writeFileSync(path.join(outDir, "dhp-tokens.css"), cssLines.join("\n"), "utf8");
console.log(`Synced bundle and token CSS to ${path.relative(process.cwd(), outDir)}`);
